# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4b6fb87d2dbc5f5f839d43bef28cc5f56b38f8d58e1cbed443c3584323ee67d9e8f45f325f867701d3e64f117404d0f916e26f652d0dbceb107ad2faeff7f79

test:
  secret_key_base: 77d8a98d67d7c0d4f1926f698beba0eaee6fc0090be8a39542606704e1534b3cef37d6400e7dc45b9955424de3f1de6e1f7b446189a942aa48b6966c24b7f54b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
